apiVersion: v1
data:
  access-log-path: /var/log/nginx/access.log
  add-headers: ingress-nginx/custom-headers
  allow-snippet-annotations: 'true'
  client-body-buffer-size: 128k
  client-body-timeout: '60'
  client-header-timeout: '60'
  enable-brotli: 'true'
  enable-real-ip: 'true'
  error-log-path: /var/log/nginx/error.log
  forwarded-for-header: CF-Connecting-IP
  gzip-level: '6'
  gzip-types: >-
    application/atom+xml application/javascript application/json
    application/rss+xml application/vnd.ms-fontobject application/x-font-ttf
    application/x-web-app-manifest+json application/xhtml+xml application/xml
    font/opentype image/svg+xml image/x-icon text/css text/javascript text/plain
    text/x-component
  hide-headers: 'Server,X-Powered-By'
  http-snippet: |
    map $upstream_response_time $n_urt { default -1; ~^(?<v>[0-9]+(\.[0-9]+)?) $v; }
    map $upstream_connect_time $n_uct { default -1; ~^(?<v>[0-9]+(\.[0-9]+)?) $v; }
    map $upstream_header_time $n_uht { default -1; ~^(?<v>[0-9]+(\.[0-9]+)?) $v; }
    map $upstream_response_length $n_url { default -1; ~^(?<v>[0-9]+(\.[0-9]+)?) $v; }
    map $upstream_status $n_us { default -1; ~^(?<v>[0-9]+) $v; }
  keepalive-requests: '100'
  keepalive-timeout: '75'
  large-client-header-buffers: 4 16k
  log-format-escape-json: 'true'
  log-format-upstream: >-
    {"time_iso8601":"$time_iso8601","request_id":"$req_id","remote_addr":"$remote_addr","realip_remote_addr":"$realip_remote_addr","cf_ray":"$http_cf_ray","cf_connecting_ip":"$http_cf_connecting_ip","cf_ipcountry":"$http_cf_ipcountry","request_method":"$request_method","domain":"$host","uri":"$uri","request_uri":"$request_uri","scheme":"$scheme","status":$status,"body_bytes_sent":$body_bytes_sent,"bytes_sent":$bytes_sent,"remote_user":"$remote_user","http_referer":"$http_referer","http_user_agent":"$http_user_agent","http_x_forwarded_for":"$http_x_forwarded_for","request_length":$request_length,"request_time":$request_time,"proxy_upstream_name":"$proxy_upstream_name","proxy_alternative_upstream_name":"$proxy_alternative_upstream_name","upstream_addr":"$upstream_addr","upstream_status":$n_us,"upstream_connect_time":$n_uct,"upstream_header_time":$n_uht,"upstream_response_time":$n_urt,"upstream_response_length":$n_url,"ssl_protocol":"$ssl_protocol"}
  map-hash-bucket-size: '128'
  max-worker-open-files: '65535'
  proxy-body-size: 50m
  proxy-buffer-size: 16k
  proxy-buffers-number: '8'
  proxy-connect-timeout: '60'
  proxy-read-timeout: '60'
  proxy-real-ip-cidr: >-
    173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22,2400:cb00::/32,2606:4700::/32,2803:f800::/32,2405:b500::/32,2405:8100::/32,2a06:98c0::/29,2c0f:f248::/32,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,100.0.0.0/8
  proxy-send-timeout: '60'
  ssl-ciphers: >-
    ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
  ssl-prefer-server-ciphers: 'true'
  ssl-protocols: TLSv1.2 TLSv1.3
  ssl-session-cache: 'true'
  ssl-session-cache-size: 10m
  ssl-session-timeout: 10m
  upstream-keepalive-connections: '32'
  upstream-keepalive-timeout: '60'
  use-forwarded-headers: 'true'
  worker-connections: '65535'
  worker-processes: auto
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.11.3
  name: ingress-nginx-controller
  namespace: ingress-nginx
