

apiVersion: v1
kind: Secret
metadata:
  name: db-lianantech-hk-release-db-credentials
  namespace: db-lianantech-hk-release
  labels:
    product: db
    version: lianantech
    branch: hk
    env: release
    app.kubernetes.io/component: database-credentials
    app.kubernetes.io/managed-by: deployment-system
  annotations:
    deployment-system/version: lianantech
    deployment-system/environment: release
    deployment-system/secret-type: database
    deployment-system/description: "Database credentials for db in release environment"
type: Opaque
data:

  MYSQL_API_USERNAME: YXBpX3VzZXI=

  MYSQL_API_PASSWORD: T01Qd3BVMzRPbEhTWFZJNA==

  MYSQL_TRACE_USERNAME: cm9vdA==

  MYSQL_TRACE_PASSWORD: elRjS3diS0NDUnlxQWczdmxVMmc=

  MYSQL_KYA_USERNAME: a3lhX3VzZXI=

  MYSQL_KYA_PASSWORD: QjhYWWZlSmkzNXJkVlVkbQ==

  MYSQL_KYT_USERNAME: a3l0X3VzZXI=

  MYSQL_KYT_PASSWORD: TmE3TUFPNnpOVWVVZVFiMA==

  MYSQL_BMS_USERNAME: cm9vdA==

  MYSQL_BMS_PASSWORD: elRjS3diS0NDUnlxQWczdmxVMmc=

  MYSQL_COMMON_USERNAME: cm9vdA==

  MYSQL_COMMON_PASSWORD: elRjS3diS0NDUnlxQWczdmxVMmc=

  MYSQL_USER_USERNAME: cm9vdA==

  MYSQL_USER_PASSWORD: elRjS3diS0NDUnlxQWczdmxVMmc=

  MYSQL_XXLJOBADMIN_USERNAME: cm9vdA==

  MYSQL_XXLJOBADMIN_PASSWORD: elRjS3diS0NDUnlxQWczdmxVMmc=

  REDIS_API_PASSWORD: I0I3UFRhZ0ExQjYjKnBMQHJ3SiM=

  REDIS_TRACE_PASSWORD: I0I3UFRhZ0ExQjYjKnBMQHJ3SiM=

  REDIS_BMS_PASSWORD: I0I3UFRhZ0ExQjYjKnBMQHJ3SiM=

  REDIS_KYA_PASSWORD: I0I3UFRhZ0ExQjYjKnBMQHJ3SiM=

  REDIS_KYT_PASSWORD: I0I3UFRhZ0ExQjYjKnBMQHJ3SiM=

  REDIS_COMMON_PASSWORD: I0I3UFRhZ0ExQjYjKnBMQHJ3SiM=

  REDIS_USER_PASSWORD: I0I3UFRhZ0ExQjYjKnBMQHJ3SiM=

  ELASTICSEARCH_API_PASSWORD: MTBHS1Q3bVAxMWczVFJpTg==

  ELASTICSEARCH_BMS_PASSWORD: MTBHS1Q3bVAxMWczVFJpTg==

  ELASTICSEARCH_COMMON_PASSWORD: MTBHS1Q3bVAxMWczVFJpTg==

  ELASTICSEARCH_KYA_PASSWORD: MTBHS1Q3bVAxMWczVFJpTg==

  ELASTICSEARCH_KYT_PASSWORD: MTBHS1Q3bVAxMWczVFJpTg==

  ELASTICSEARCH_TRACE_PASSWORD: MTBHS1Q3bVAxMWczVFJpTg==

  ELASTICSEARCH_USER_PASSWORD: MTBHS1Q3bVAxMWczVFJpTg==

  ELASTICSEARCH_XXLJOBADMIN_PASSWORD: MTBHS1Q3bVAxMWczVFJpTg==

